spring.application.name=kindergarten_g3
spring.datasource.url=jdbc:mysql://kintergarden-db.c7eyqgsos2l7.ap-southeast-1.rds.amazonaws.com:3306/instance_kintergarden_db
spring.datasource.username=admin
spring.datasource.password=KintergardenDatabase
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Hibernate config
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate

#Message config
spring.config.import= messages.properties

#port
server.port=8080

# Cloudinary Config
cloudinary.cloud-name=dll6ocdhe
cloudinary.api-key=462197591487523
cloudinary.api-secret=7UbXkkyhKAp3eBS6A-gwx50fyIE

#email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngtuananh.1104@gmail.com
spring.mail.password=kgrf artb zsvg wtba
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true